#define HTTP_ERROR_MEM_ALLOC_FAILED 1
#define HTTP_ERROR_NULL_POINTER 2
#define HTTP_ERROR_INVALID_REQUEST_TYPE 3
#define HTTP_ERROR_SOCKET_CREATION_FAILED 4
#define HTTP_ERROR_SERVER_CONN_FAILED 5
#define HTTP_ERROR_SOCKET_WRITE_FAILED 6
#define HTTP_ERROR_REC_FAILED 7
